use crate::db::models::ParsedVariable;
use crate::error::{AppError, Result};

pub fn parse_env_file(content: &str) -> Result<Vec<ParsedVariable>> {
    let mut results = Vec::new();
    let mut pending_comment: Option<String> = None;

    for line in content.lines() {
        let trimmed = line.trim();


        if trimmed.is_empty() {
            pending_comment = None;
            continue;
        }


        if trimmed.starts_with('#') {
            let comment = trimmed.trim_start_matches('#').trim().to_string();
            if !comment.is_empty() {
                pending_comment = Some(comment);
            }
            continue;
        }


        let line_stripped = trimmed.strip_prefix("export ").unwrap_or(trimmed).trim();


        let eq_pos = line_stripped.find('=').ok_or_else(|| {
            AppError::InvalidEnvFile(format!("Line has no '=': {}", trimmed))
        })?;

        let key = line_stripped[..eq_pos].trim().to_string();
        let raw_value = line_stripped[eq_pos + 1..].trim();

        if key.is_empty() {
            return Err(AppError::InvalidEnvFile("Empty key".into()));
        }


        let value = unquote(raw_value);

        let description = pending_comment.take();

        results.push(ParsedVariable { key, value, description });
    }

    Ok(results)
}

fn unquote(s: &str) -> String {

    if s.starts_with('"') && s.ends_with('"') && s.len() >= 2 {
        let inner = &s[1..s.len() - 1];
        return inner.replace("\\n", "\n").replace("\\\"", "\"").replace("\\\\", "\\");
    }

    if s.starts_with('\'') && s.ends_with('\'') && s.len() >= 2 {
        return s[1..s.len() - 1].to_string();
    }

    if let Some(pos) = s.find(" #") {
        return s[..pos].trim().to_string();
    }
    s.to_string()
}

pub fn generate_env_file(pairs: &[(String, String, Option<String>)], project_name: &str, tier_name: &str) -> String {
    let mut out = String::new();
    let now = chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ");
    out.push_str(&format!("# Generated by EnvVault — {}\n", now));
    out.push_str(&format!("# Project: {} | Tier: {}\n", project_name, tier_name));
    out.push_str("# DO NOT COMMIT THIS FILE\n\n");

    let mut sorted: Vec<_> = pairs.to_vec();
    sorted.sort_by(|a, b| a.0.cmp(&b.0));

    for (key, value, desc) in &sorted {
        if let Some(d) = desc {
            if !d.is_empty() {
                out.push_str(&format!("# {}\n", d));
            }
        }

        if value.contains('"') || value.contains('\n') {
            let escaped = value.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n");
            out.push_str(&format!("{}=\"{}\"\n", key, escaped));
        } else if value.contains(' ') || value.is_empty() {
            out.push_str(&format!("{}=\"{}\"\n", key, value));
        } else {
            out.push_str(&format!("{}={}\n", key, value));
        }
    }

    out
}
